image:
    file: gitpod.Dockerfile
ports:
  - port: 8888
    onOpen: ignore
  - port: 4502
    onOpen: ignore
tasks:
  - init: "mkdir -p /tmp/aplkernel && \
    git clone https://github.com/Dyalog/dyalog-jupyter-kernel.git /tmp/aplkernel && \
    /tmp/aplkernel/dyalog-jupyter-kernel/install.sh"
    command: "jupyter notebook --NotebookApp.allow_origin=$(gp url 8888)"
