image:
    file: gitpod.Dockerfile
ports:
  - port: 8888
    onOpen: ignore
  - port: 4502
    onOpen: ignore
tasks:
  - init: "mkdir -p /tmp/aplkernel && \
    git clone https://github.com/Dyalog/dyalog-jupyter-kernel.git /tmp/aplkernel && \
    /tmp/aplkernel/install.sh"
    command: "./start_jupyter_gitpod.sh"
